config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users

  root to: "home#index"

  resources :surveys 
  resources :questions
  resources :answers, only: :create
  resources :options 

  resources :response_surveys do 
    get :complete_survey, on: :member
  end 

  get 'result', to: 'response_surveys#result'
  
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
    has_many :answer_options, dependent: :destroy 
    has_many :options, through: :answer_options, dependent: :destroy 
end

app/models/answer_option.rb
class AnswerOption < ApplicationRecord
    belongs_to :answer
    belongs_to :option
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/option.rb
class Option < ApplicationRecord
    has_many :answer_options, dependent: :destroy 
    has_many :answers, through: :answer_options, dependent: :destroy 
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :survey
    has_many :options, dependent: :destroy
    has_many :answers, dependent: :destroy  

    enum question_type: { multi_choice: 0, selected_choice: 1, open_ended: 2 }
end

app/models/response_survey.rb
class ResponseSurvey < ApplicationRecord
    belongs_to :survey
    
    has_many :answers
end

app/models/survey.rb
class Survey < ApplicationRecord
    before_save :cap_create
    has_many :questions, dependent: :destroy 
    has_many :response_surveys, dependent: :destroy 

    private 
    def cap_create
        self.title = title.capitalize
    end 
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  enum roles: { admin: 0, designer: 1, taker: 2 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :authenticate_user!

    def create 
        @answer = Answer.new(answer_params)
        @question = Question.find(answer_params[:question_id])
        @survey = Survey.find(params[:survey_id])
        @response_survey = ResponseSurvey.find(params[:response_survey_id])

        if @answer.save
            flash[:success] = "Question Saved!"
            redirect_to complete_survey_response_survey_path(id: @response_survey.id, survey_id: @survey.id)
        else 
            flash[:alert] = "Question creation failed"
        end 
        authorize @answer
    end 

    private 
    def answer_params
        params.permit(:choice, :multi, :reply, :response_survey_id, :question_id, option_ids: [])
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
    private
    def user_not_authorized
      flash[:alert] = 'You are not authorized to perform this action.'
      # redirect_to root_path and return
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
    def new 
        @question = Question.find(params[:question_id])
        @option = @question.options.new
        authorize @option 
    end 

    def create 
        @question = Question.find(option_params[:question_id])
        @option = @question.options.create(option_params)

        if @option.save
            redirect_to @question
        else 
            render :new 
        end 
        authorize @option
    end 

    private 
    def option_params
        params.require(:option).permit(:choice, :question_id)
    end 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :authenticate_user!
    def index 
        @questions = Question.all 
        authorize @questions
    end 

    def show 
        @question = Question.find(params[:id])
        authorize @question
    end 

    def new 
        @question = Question.new 
        @survey = Survey.find(params[:survey_id])
        authorize @question
    end 

    def create 
        @question = Question.new(question_params)
        @survey = Survey.find(question_params[:survey_id])

        if @question.save
            redirect_to @question
        else 
            render :new 
        end 
        authorize @question
    end 

    def edit 
        @question = Question.find(params[:id])
        @survey = Survey.find(params[:survey_id])
        authorize @question
    end 

    def update 
        @question = Question.find(params[:id])
        @survey = Survey.find(question_params[:survey_id])

        if @question.update(question_params)
            redirect_to @question 
        else 
            render :edit 
        end 
        authorize @question
    end 

    def destroy 
        @question = Question.find(params[:id])
        @question.destroy 

        redirect_to surveys_path 
        authorize @question
    end 

    private 
    def question_params
        params.require(:question).permit(:main_question, :survey_id, :question_type)
    end 
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
    before_action :authenticate_user!
    def index 
        @surveys = Survey.all 
        authorize @surveys
    end 

    def show 
        @survey = Survey.find(params[:id])
        authorize @survey
    end 

    def new 
        @survey = Survey.new 
        authorize @survey
    end 

    def create 
        @survey = Survey.new(survey_params)

        if @survey.save 
            redirect_to @survey
        else 
            render :new 
        end 
        authorize @survey
    end 

    def edit 
        @survey = Survey.find(params[:id])
        authorize @survey
    end 

    def update 
        @survey = Survey.find(params[:id])

        if @survey.update(survey_params)
            redirect_to @survey 
        else 
            render :edit 
        end 
        authorize @survey
    end 

    def destroy 
        @survey = Survey.find(params[:id])
        @survey.destroy 

        redirect_to surveys_path 
        authorize @survey
    end 

    private 
    def survey_params
        params.require(:survey).permit(:title)
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/response_surveys_helper.rb
module ResponseSurveysHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/options/new.html.slim
h1 
    | New Option 

= form_with model: @option do |form|
    = form.label "Option"
    br 
    = form.text_field :choice
    br 
    = form.hidden_field :question_id, value: @question.id
    br 
    =form.submit 

app/views/questions/_form.html.slim
= form_with model: @question do |form|
    = form.label "Question"
    = form.text_field :main_question
    br 
    = form.hidden_field :survey_id, value: @survey.id
    br 
    = form.label "Question Type"
    = form.select :question_type, Question.question_types.map { |key, value| [key.titleize, Question.question_types.key(value)]}, include_blank: true
    br 
    =form.submit 

app/views/questions/edit.html.slim
h1 
    |  Edit question

=render "form", question: @question

app/views/questions/new.html.slim
h1 
    |  New question

=render "form", question: @question

app/views/questions/show.html.slim
h1 
    =@question.main_question 

h2 
    =@question.question_type
    br 
    br 
    -@question.options.each do |option|
        li 
            =option.choice

br 
=link_to "New choice", new_option_path(question_id: @question.id)
br 
=link_to "All surveys", surveys_path 

app/views/surveys/_form.html.slim
= form_for(@survey) do |form|
    = form.label "Name of survey"
    = form.text_field :title 
        
    = form.submit

app/views/surveys/edit.html.slim
h1 
    |  Edit Survey

=render "form", survey: @survey

app/views/surveys/index.html.slim
h1 
    |  Surveys

h2 
    -@surveys.each do |survey|
        =link_to survey.title, survey 
        br 
br  
-if current_user.roles == "admin" || current_user.roles == "designer"
    =link_to "New Survey", new_survey_path

app/views/surveys/new.html.slim
h1 
    |  New Survey

=render "form", survey: @survey

app/views/surveys/show.html.slim
h1 
    =@survey.title 
    br 
        h4
            -if current_user.roles == 'taker'
            
            -else 
                =link_to "Edit survey", edit_survey_path(@survey)
                br 
                =link_to "Delete survey", survey_path(@survey),
                            method: :delete,
                            data: { confirm: "Are you sure?" }

h2 
    -@survey.questions.each do |question|
        li 
            =link_to question.main_question, question

            ul 
                h6
                    -if current_user.roles == 'taker'
            
                    -else 
                        =link_to "Edit Question", edit_question_path(question, survey_id: @survey.id)
                        br 
                        =link_to "Delete Question", question_path(question), method: :delete, data: { confrim: "Are you sure?" }

-if current_user.roles == 'admin' || current_user.roles == 'designer'
    =link_to "Add Question", new_question_path(survey_id: @survey.id)
    br 
    =link_to "Survey result", result_path(survey_id: @survey.id)
    br
    =link_to "All surveys", surveys_path
-else  
    =link_to "Start survey", response_surveys_path(survey_id: @survey.id), method: :post