config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users

  root to: "home#index"

  resources :surveys 
  resources :questions
  resources :answers, only: :create
  resources :options 

  resources :response_surveys do 
    get :complete_survey, on: :member
  end 

  get 'result', to: 'response_surveys#result'
  
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
    has_many :answer_options, dependent: :destroy 
    has_many :options, through: :answer_options, dependent: :destroy 
end

app/models/answer_option.rb
class AnswerOption < ApplicationRecord
    belongs_to :answer
    belongs_to :option
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/option.rb
class Option < ApplicationRecord
    has_many :answer_options, dependent: :destroy 
    has_many :answers, through: :answer_options, dependent: :destroy 
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :survey
    has_many :options, dependent: :destroy
    has_many :answers, dependent: :destroy  

    enum question_type: { multi_choice: 0, selected_choice: 1, open_ended: 2 }
end

app/models/response_survey.rb
class ResponseSurvey < ApplicationRecord
    belongs_to :survey
    
    has_many :answers
end

app/models/survey.rb
class Survey < ApplicationRecord
    before_save :cap_create
    has_many :questions, dependent: :destroy 
    has_many :response_surveys, dependent: :destroy 

    private 
    def cap_create
        self.title = title.capitalize
    end 
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  enum roles: { admin: 0, designer: 1, taker: 2 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :authenticate_user!

    def create 
        @answer = Answer.new(answer_params)
        @question = Question.find(answer_params[:question_id])
        @survey = Survey.find(params[:survey_id])
        @response_survey = ResponseSurvey.find(params[:response_survey_id])

        if @answer.save
            flash[:success] = "Question Saved!"
            redirect_to complete_survey_response_survey_path(id: @response_survey.id, survey_id: @survey.id)
        else 
            flash[:alert] = "Question creation failed"
        end 
        authorize @answer
    end 

    private 
    def answer_params
        params.permit(:choice, :multi, :reply, :response_survey_id, :question_id, option_ids: [])
    end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
    def new 
        @question = Question.find(params[:question_id])
        @option = @question.options.new
        authorize @option 
    end 

    def create 
        @question = Question.find(option_params[:question_id])
        @option = @question.options.create(option_params)

        if @option.save
            redirect_to @question
        else 
            render :new 
        end 
        authorize @option
    end 

    private 
    def option_params
        params.require(:option).permit(:choice, :question_id)
    end 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :authenticate_user!
    def index 
        @questions = Question.all 
        authorize @questions
    end 

    def show 
        @question = Question.find(params[:id])
        authorize @question
    end 

    def new 
        @question = Question.new 
        @survey = Survey.find(params[:survey_id])
        authorize @question
    end 

    def create 
        @question = Question.new(question_params)
        @survey = Survey.find(question_params[:survey_id])

        if @question.save
            redirect_to @question
        else 
            render :new 
        end 
        authorize @question
    end 

    def edit 
        @question = Question.find(params[:id])
        @survey = Survey.find(params[:survey_id])
        authorize @question
    end 

    def update 
        @question = Question.find(params[:id])
        @survey = Survey.find(question_params[:survey_id])

        if @question.update(question_params)
            redirect_to @question 
        else 
            render :edit 
        end 
        authorize @question
    end 

    def destroy 
        @question = Question.find(params[:id])
        @question.destroy 

        redirect_to surveys_path 
        authorize @question
    end 

    private 
    def question_params
        params.require(:question).permit(:main_question, :survey_id, :question_type)
    end 
end

app/controllers/response_surveys_controller.rb
class ResponseSurveysController < ApplicationController
    before_action :authenticate_user!

    def create 
        @survey = Survey.find(params[:survey_id])
        @response_survey = @survey.response_surveys.create 
        @response_survey.save 
        redirect_to complete_survey_response_survey_path(id: @response_survey.id, survey_id: @survey.id)
        authorize @response_survey
    end 

    def complete_survey 
        @survey = Survey.find(params[:survey_id])
        @questions = @survey.questions.all 
        @response_survey = @survey.response_surveys.find(params[:id])
        question_ids = Answer.where(response_survey_id: @response_survey, question_id: @questions).pluck(:question_id)
        all_ids = @questions.ids
        unanswered_questions = all_ids - question_ids 
        if unanswered_questions.blank?
            flash[:success] = "Survey Completed!"
            redirect_to surveys_path
        else 
            @question = Question.find(unanswered_questions.first)
        end 
    end 

    def result
        @survey = Survey.find(params[:survey_id])
        @questions = @survey.questions.all
    end 
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
    before_action :authenticate_user!
    def index 
        @surveys = Survey.all 
        authorize @surveys
    end 

    def show 
        @survey = Survey.find(params[:id])
        authorize @survey
    end 

    def new 
        @survey = Survey.new 
        authorize @survey
    end 

    def create 
        @survey = Survey.new(survey_params)

        if @survey.save 
            redirect_to @survey
        else 
            render :new 
        end 
        authorize @survey
    end 

    def edit 
        @survey = Survey.find(params[:id])
        authorize @survey
    end 

    def update 
        @survey = Survey.find(params[:id])

        if @survey.update(survey_params)
            redirect_to @survey 
        else 
            render :edit 
        end 
        authorize @survey
    end 

    def destroy 
        @survey = Survey.find(params[:id])
        @survey.destroy 

        redirect_to surveys_path 
        authorize @survey
    end 

    private 
    def survey_params
        params.require(:survey).permit(:title)
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/response_surveys_helper.rb
module ResponseSurveysHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/response_surveys/complete_survey.html.slim
=form_with model: @answer, url: answers_path, method: :post do |f|
    h2     
        =f.label @question.main_question
        br
        =f.hidden_field :survey_id, value: @survey.id
        =f.hidden_field :question_id, value: @question.id
        =f.hidden_field :response_survey_id, value: @response_survey.id

        - if @question.question_type == 'multi_choice'
            =f.select :multi, @question.options.all.collect { |option| [option.choice, option.id] }, include_blank: true 
            br  

        - elsif @question.question_type == 'selected_choice'
            h4
                = f.collection_check_boxes :option_ids, @question.options.all, :id, :choice do |x|
                    = x.check_box
                    = x.label
                    br 
    
        - elsif @question.question_type == 'open_ended' 
            =f.label "Answer"
            br
            =f.text_area :reply 
            br

        = f.submit ("Submit")

app/views/response_surveys/new.html.slim
=form_for @response_survey do |f|
    h2     
        =f.label @question.main_question
        br
        =f.hidden_field :survey_id, value: @survey.id
        =f.hidden_field :question_id, value: @question.id

        - if @question.question_type == 'multi_choice'
            =f.select :answer_id, @question.answers.all.collect { |answer| [answer.choice, answer.id] }, include_blank: true 
            br  
            h5 
                =f.label "Other"
                br
                =f.text_area :response 


        - elsif @question.question_type == 'selected_choice'
            h4
                = f.collection_check_boxes :answer_ids, @question.answers.all, :id, :choice do |x|
                    = x.check_box
                    = x.label
                    br 
            br 
            h5
                =f.label "Other"
                br
                =f.text_area :response 

    
        - elsif @question.question_type == 'open_ended' 
            =f.label "Answer"
            br
            =f.text_area :response 
            br

        = f.submit ("Submit")

app/views/response_surveys/result.html.slim
h1 
    |   Results of survey #{@survey.title}
 


-@questions.each do |question|
    h2 
        =question.main_question 
        br
        -arr = []
        -question.options.each do |option|
            -arr.push(option.choice)
        h3 
            | Possible choices
        -arr.each do |element|
            =element
            | /  
        h3 
            | Actual response/s 
        -arr2 = []
        -question.answers.each do |answer|
            - if answer.option_ids.present?
                - result = Option.find(answer.option_ids)
                - result.each {|result| arr2.push(result.choice)}
            - if answer.multi.present?
                - result = Option.find(answer.multi)
                - arr2.push(result.choice)
            -if answer.reply.present?
                = answer.reply
                br
        - arr.each do |element|
            - count = arr2.count(element).to_f
            - percentage = ((count/arr2.length)*100)
            - if percentage.nan? == false
                ="#{percentage.to_i}% " 
                | : 
                ="#{(count).to_i} response/s for #{element}"
            - else 
                | No data
            br     

br
=link_to "All Surveys", surveys_path